/**********************************************************************
Name: EDGE_UtilityClassExtended
=======================================================================
Req: EDGE_UtilityClassExtended
=======================================================================
History                                                            
-------                                                            
VERSION   AUTHOR            DATE              DETAIL
1.0   Monalisa Halder     23/02/2021         ES20-9804
***********************************************************************/
public with sharing class EDGE_UtilityClassExtended {
    
    //Variable to stop trigger recursion 
    public static boolean stopTriggerRunfromRepInsertBatch=false;

}