/*
* @description :  EDGE_CallTraxStatusUpdateHelper

* @purpose : This is the Helper class for the batch class EDGE_CallTraxStatusUpdateBatch

* @Test Class: EDGE_CallTraxStatusUpdateBatchTest

* @history :

* Version    Developer         		Date           			  User Story/Purpose
  1.0		 Dipanjan Das			24.06.2024			      155391 -- To fix the SCA of EDGE_CallTraxStatusUpdateBatch
*/
public without Sharing class EDGE_CallTraxStatusUpdateHelper {
	
}